### ISSUE TITLE
"provided-by" links between service and software components flagged

### ISSUE THREAD

**Issue by Telos-sa** [metaschema-framework/oscal-cli#35]
# Describe the bug

Bug description and replication steps are outlined in [NIST OSCAL Repo issue 2046](https://github.com/usnistgov/OSCAL/issues/2046)

uuid "provided-by" references between these 2 components appear to be getting flagged incorrectly

**Comment by david-waltermire** [comment]
@Telos-sa It looks like you are using an older version of OSCAL CLI. Please try the test again using a [recent version](https://github.com/metaschema-framework/oscal-cli/releases/tag/v2.1.0).

**Comment by david-waltermire** [comment]
No response from @Telos-sa. Going to close this for now. We can reopen if new information is made available.
