### ISSUE TITLE
FedRAMP external constraints validating by-component at wrong layer

### ISSUE THREAD

**Issue by Telos-sa** [metaschema-framework/oscal-cli#55]
In the [FedRAMP OSCAL Documentation](https://automate.fedramp.gov/documentation/ssp/6-security-controls/) it outlines that by-component elements should be at the statements level (control-implementation>implemented-requirements>statements).
<img width="912" alt="Screenshot 2024-10-08 at 4 31 55 PM" src="https://github.com/user-attachments/assets/92956ffa-70f5-4ca4-90ac-2a7527a4ffc1">
We have our OSCAL formatted as outlined in the documentation, but when validating using the enhanced oscal-cli and the fedramp-external-constraints.xml, it flags this as an incorrect structure. It instead gives the following errors, which suggests that these by-component elements should be at the implemented-requirements level rather than statements.
<img width="692" alt="Screenshot 2024-10-08 at 4 41 48 PM" src="https://github.com/user-attachments/assets/00ec85e0-422c-4822-a2a4-c78aa3e31de6">
We were hoping you could help us identify whether this is a bug, or a formatting issue with our OSCAL. Here is a snippet of the OSCAL that is causing these validation errors:
```
"implemented-requirements":[
  {
    "uuid":"5b55e601-fa5c-58fc-9596-f8e4ee1cccfc",
    "control-id":"ac-3",
    "props":[
        {
            "name":"control-origination",
            "ns":"https://fedramp.gov/ns/oscal",
            "value":"sp-corporate"
        },
        {
            "name":"control-origination",
            "ns":"https://fedramp.gov/ns/oscal",
            "value":"sp-system"
        },
        {
            "name":"control-origination",
            "ns":"https://fedramp.gov/ns/oscal",
            "value":"customer-configured"
        },
        {
            "name":"implementation-status",
            "ns":"https://fedramp.gov/ns/oscal",
            "value":"implemented"
        }
    ],
    "statements":[
        {
            "statement-id":"ac-3_smt",
            "uuid":"554572df-8a52-54da-803c-170d246f6c3b",
            "by-components":[
                {
                    "component-uuid":"c0e9b4ab-7f2e-54da-9cb3-72894240cc3f",
                    "uuid":"f9086f0c-a65d-597c-9c59-88cf02b30c27",
                    "description":"Private Implementation details and description for the following control statement: AC-03",
                    "implementation-status":{
                        "state":"implemented"
                    },
                    "export":{
                        "provided":[
                            {
                                "uuid":"c39e10b2-28ae-586c-9a2a-93c2983d57c7",
                                "description":"<p>This is what is shared with the customer on export, and what the customer configures<br />\n</p>"
                            }
                        ]
                    }
                }
            ]
        }
    ]
  }
]
```

**Comment by david-waltermire** [comment]
This looks like a potential FedRAMP constraints issue. @Rene2mt or @aj-stein-gsa any feedback?

**Comment by aj-stein-gsa** [comment]
> This looks like a potential FedRAMP constraints issue. @Rene2mt or @aj-stein-gsa any feedback?

Agreed. Seems like we can transfer issues across repos. I will have to manually recreate this issue in GSA/fedramp-automation. Apologies. I will close this once I copy-paste it to "transfer" the issue.

**Comment by aj-stein-gsa** [comment]
Closing this issue, replacing it with https://github.com/GSA/fedramp-automation/issues/770 in the appropriate location.
